from __future__ import annotations

from types import SimpleNamespace

from agent_platform.executors import (
    ExecutorRegistry,
    HumanGateExecutor,
    LLMGenerateExecutor,
    LLMReviewExecutor,
)
from agent_platform.runtime.context_manager import ExecutionContextManager
from agent_platform.runtime.events import (
    NODE_STATUS_FAILED,
    NODE_STATUS_PENDING,
    NODE_STATUS_SUCCEEDED,
    NODE_STATUS_WAITING_HUMAN,
    WORKFLOW_STATUS_SUCCEEDED,
)
from agent_platform.runtime.human_gate_service import HumanGateService
from agent_platform.runtime.records_manager import ExecutionRecordsManager
from agent_platform.runtime.rerun import RerunService


def _build_registry() -> ExecutorRegistry:
    registry = ExecutorRegistry()
    registry.register("llm_generate", LLMGenerateExecutor())
    registry.register("llm_review", LLMReviewExecutor())
    registry.register("human_gate", HumanGateExecutor())
    return registry


def _make_node(
    node_id: str,
    node_type: str,
    *,
    input_from: list[dict[str, str]] | None = None,
    config: dict | None = None,
):
    return SimpleNamespace(
        id=node_id,
        type=node_type,
        input={"from": input_from or []},
        config=config or {},
    )


def _run_node(
    *,
    execution_id: str,
    node,
    context_manager: ExecutionContextManager,
    records_manager: ExecutionRecordsManager,
    registry: ExecutorRegistry,
    gate_service: HumanGateService,
):
    context = context_manager.get_context(execution_id)
    records_manager.start_node_record(execution_id, node.id, node.type)

    executor = registry.resolve_for_node(node)
    result = executor.execute(context, node)

    for log in result.logs:
        records_manager.append_node_log(execution_id, node.id, log)
        context_manager.append_log(execution_id, f"{node.id}: {log}")

    if result.output:
        context_manager.set_node_output(execution_id, node.id, result.output)

    if result.status == NODE_STATUS_WAITING_HUMAN:
        gate_service.mark_waiting(execution_id, node.id, comment="waiting for review")
    elif result.status == NODE_STATUS_SUCCEEDED:
        context_manager.update_node_state(execution_id, node.id, NODE_STATUS_SUCCEEDED)
        records_manager.complete_node_record(
            execution_id,
            node.id,
            output_preview=executor.summarize_output(result),
        )
    elif result.status == NODE_STATUS_FAILED:
        context_manager.update_node_state(execution_id, node.id, NODE_STATUS_FAILED)
        records_manager.fail_node_record(
            execution_id,
            node.id,
            error_message=result.error_message or "executor failed",
        )
    else:
        raise AssertionError(f"Unexpected executor status: {result.status}")

    return result


def test_phase2_runtime_flow_normal_approval() -> None:
    context_manager = ExecutionContextManager()
    records_manager = ExecutionRecordsManager()
    gate_service = HumanGateService(records_manager, context_manager)
    registry = _build_registry()

    context = context_manager.create_context(
        workflow_id="wf_phase2",
        workflow_version="v2",
        global_inputs={"task": "draft a summary"},
    )
    execution_id = context.execution_id
    records_manager.create_workflow_record(execution_id, "wf_phase2", "v2")

    generate_node = _make_node("generate", "llm_generate")
    gate_node = _make_node(
        "approve_draft",
        "human_gate",
        input_from=[{"node": "generate", "key": "result"}],
    )
    gate_service.register_workflow_definition(
        execution_id,
        [{"id": "generate"}, {"id": "approve_draft", "config": {}}],
    )

    generate_result = _run_node(
        execution_id=execution_id,
        node=generate_node,
        context_manager=context_manager,
        records_manager=records_manager,
        registry=registry,
        gate_service=gate_service,
    )
    assert generate_result.status == NODE_STATUS_SUCCEEDED
    generated_text = context_manager.get_context(execution_id).node_outputs["generate"]["result"]
    assert isinstance(generated_text, str)
    assert "generated by generate" in generated_text

    gate_result = _run_node(
        execution_id=execution_id,
        node=gate_node,
        context_manager=context_manager,
        records_manager=records_manager,
        registry=registry,
        gate_service=gate_service,
    )
    assert gate_result.status == NODE_STATUS_WAITING_HUMAN

    gate_record = records_manager.get_node_record(execution_id, "approve_draft")
    assert gate_record.status == NODE_STATUS_WAITING_HUMAN
    assert gate_record.requires_human_action is True

    approved = gate_service.approve(execution_id, "approve_draft", comment="approved")
    assert approved == WORKFLOW_STATUS_SUCCEEDED or approved == NODE_STATUS_SUCCEEDED

    workflow_record = records_manager.set_workflow_status(execution_id, WORKFLOW_STATUS_SUCCEEDED)
    assert workflow_record.status == WORKFLOW_STATUS_SUCCEEDED
    assert records_manager.get_node_record(execution_id, "approve_draft").status == NODE_STATUS_SUCCEEDED


def test_phase2_runtime_flow_reject_then_prepare_rerun() -> None:
    context_manager = ExecutionContextManager()
    records_manager = ExecutionRecordsManager()
    gate_service = HumanGateService(records_manager, context_manager)
    rerun_service = RerunService(context_manager, records_manager)
    registry = _build_registry()

    context = context_manager.create_context(workflow_id="wf_phase2", workflow_version="v2")
    execution_id = context.execution_id
    records_manager.create_workflow_record(execution_id, "wf_phase2", "v2")

    prep_node = _make_node("prepare", "llm_generate")
    draft_node = _make_node("draft", "llm_generate")
    gate_node = _make_node("approval", "human_gate")
    review_node = _make_node("review", "llm_review")

    gate_service.register_workflow_definition(
        execution_id,
        [
            {"id": "prepare"},
            {"id": "draft"},
            {"id": "approval", "config": {"on_reject": "draft"}},
            {"id": "review"},
        ],
    )

    _run_node(
        execution_id=execution_id,
        node=prep_node,
        context_manager=context_manager,
        records_manager=records_manager,
        registry=registry,
        gate_service=gate_service,
    )
    _run_node(
        execution_id=execution_id,
        node=draft_node,
        context_manager=context_manager,
        records_manager=records_manager,
        registry=registry,
        gate_service=gate_service,
    )
    _run_node(
        execution_id=execution_id,
        node=gate_node,
        context_manager=context_manager,
        records_manager=records_manager,
        registry=registry,
        gate_service=gate_service,
    )

    # Simulate stale downstream outputs that should be invalidated by rerun.
    context_manager.update_node_state(execution_id, "review", NODE_STATUS_SUCCEEDED)
    context_manager.set_node_output(execution_id, "review", {"review": "stale"})
    records_manager.start_node_record(execution_id, "review", "llm_review")
    records_manager.complete_node_record(execution_id, "review", output_preview="stale")

    fallback_node_id = gate_service.reject(
        execution_id,
        "approval",
        comment="needs revision",
    )
    assert fallback_node_id == "draft"

    graph = {
        "nodes": [
            {"id": "prepare"},
            {"id": "draft"},
            {"id": "approval"},
            {"id": "review"},
        ],
        "edges": [
            {"from": "prepare", "to": "draft"},
            {"from": "draft", "to": "approval"},
            {"from": "approval", "to": "review"},
        ],
    }

    updated_context = rerun_service.prepare_rerun(execution_id, graph, fallback_node_id)

    assert updated_context.node_states["prepare"] == NODE_STATUS_SUCCEEDED
    assert updated_context.node_states["draft"] == NODE_STATUS_PENDING
    assert updated_context.node_states["approval"] == NODE_STATUS_PENDING
    assert updated_context.node_states["review"] == NODE_STATUS_PENDING

    assert "prepare" in updated_context.node_outputs
    assert "draft" not in updated_context.node_outputs
    assert "approval" not in updated_context.node_outputs
    assert "review" not in updated_context.node_outputs

    events = records_manager.find_events(execution_id)
    assert any(getattr(event, "event_type", None) == "rerun_prepared" for event in events)


def test_phase2_runtime_flow_failed_node_prepare_rerun() -> None:
    context_manager = ExecutionContextManager()
    records_manager = ExecutionRecordsManager()
    rerun_service = RerunService(context_manager, records_manager)

    context = context_manager.create_context(workflow_id="wf_phase2", workflow_version="v2")
    execution_id = context.execution_id
    records_manager.create_workflow_record(execution_id, "wf_phase2", "v2")

    # Upstream node stays intact.
    context_manager.update_node_state(execution_id, "prepare", NODE_STATUS_SUCCEEDED)
    context_manager.set_node_output(execution_id, "prepare", {"result": "ok"})
    records_manager.start_node_record(execution_id, "prepare", "llm_generate")
    records_manager.complete_node_record(execution_id, "prepare", output_preview="ok")

    # Failed node and downstream node should be reset.
    context_manager.update_node_state(execution_id, "transform", NODE_STATUS_FAILED)
    context_manager.set_node_output(execution_id, "transform", {"result": "bad"})
    records_manager.start_node_record(execution_id, "transform", "deterministic_transform")
    records_manager.fail_node_record(execution_id, "transform", error_message="invalid payload")

    context_manager.update_node_state(execution_id, "review", NODE_STATUS_SUCCEEDED)
    context_manager.set_node_output(execution_id, "review", {"review": "stale"})
    records_manager.start_node_record(execution_id, "review", "llm_review")
    records_manager.complete_node_record(execution_id, "review", output_preview="stale")

    graph = {
        "nodes": [
            {"id": "prepare"},
            {"id": "transform"},
            {"id": "review"},
        ],
        "edges": [
            {"from": "prepare", "to": "transform"},
            {"from": "transform", "to": "review"},
        ],
    }

    updated_context = rerun_service.prepare_rerun(execution_id, graph, "transform")

    assert updated_context.node_states["prepare"] == NODE_STATUS_SUCCEEDED
    assert updated_context.node_states["transform"] == NODE_STATUS_PENDING
    assert updated_context.node_states["review"] == NODE_STATUS_PENDING

    assert "prepare" in updated_context.node_outputs
    assert "transform" not in updated_context.node_outputs
    assert "review" not in updated_context.node_outputs

    transform_record = records_manager.get_node_record(execution_id, "transform")
    review_record = records_manager.get_node_record(execution_id, "review")
    assert transform_record.status == NODE_STATUS_PENDING
    assert review_record.status == NODE_STATUS_PENDING
