from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

from agent_platform.executors.llm_generate import LLMGenerateExecutor


@dataclass
class DummyContext:
    global_inputs: dict[str, Any] = field(default_factory=dict)
    node_outputs: dict[str, dict[str, Any]] = field(default_factory=dict)
    artifacts: dict[str, Any] = field(default_factory=dict)


@dataclass
class DummyNode:
    id: str
    type: str = "llm_generate"
    config: dict[str, Any] = field(default_factory=dict)
    input: dict[str, Any] = field(default_factory=dict)


def test_llm_generate_executor_returns_dummy_result() -> None:
    executor = LLMGenerateExecutor()
    context = DummyContext(global_inputs={"request": "hello"})
    node = DummyNode(id="task_understanding")

    result = executor.execute(context, node)

    assert result.status == "SUCCEEDED"
    assert isinstance(result.output.get("result"), str)
    assert "generated by task_understanding" in result.output["result"]
    assert result.input_preview == "generated by task_understanding"
    assert result.error_message is None
    assert result.logs


def test_llm_generate_executor_resolves_input_definition_from_node_output() -> None:
    executor = LLMGenerateExecutor()
    context = DummyContext(node_outputs={"planner": {"schema": "topic: string"}})
    node = DummyNode(
        id="task_understanding",
        config={
            "prompt": "Generate",
            "input_definition": "ref: planner.schema",
        },
    )

    result = executor.execute(context, node)

    assert result.status == "SUCCEEDED"
    assert isinstance(result.input_preview, str)
    assert "Input definition:\ntopic: string" in result.input_preview
