from __future__ import annotations

import json
import re
import textwrap
from collections.abc import Mapping
from typing import Any

import yaml

from agent_platform.executors.base import BaseNodeExecutor, ExecutorResult
from agent_platform.integrations.llm_adapters import (
    DummyEchoLLMAdapter,
    LLMCompletionAdapter,
    LLMCompletionRequest,
)


class LLMGenerateExecutor(BaseNodeExecutor):
    """LLM-backed executor for llm_generate nodes."""

    node_type = "llm_generate"
    _SUPPORTED_OUTPUT_FORMATS = {
        "json",
        "yaml",
        "markdown",
        "mermaid",
        "text",
        "markdown_json",
        "markdown_yaml",
        "markdown_mermaid",
    }

    def __init__(
        self,
        *,
        adapters_by_provider: Mapping[str, LLMCompletionAdapter] | None = None,
        default_adapter: LLMCompletionAdapter | None = None,
    ) -> None:
        self._adapters_by_provider = {
            str(provider): adapter for provider, adapter in (adapters_by_provider or {}).items()
        }
        self._default_adapter = default_adapter or DummyEchoLLMAdapter()

    def execute(self, context: Any, node: Any) -> ExecutorResult:
        try:
            prepared = self.prepare_input(context=context, node=node)
            node_id = getattr(node, "id", "unknown_node")

            config = prepared.get("node_config", {})
            prompt = str(config.get("prompt") or config.get("prompt_template") or "").strip()
            if not prompt:
                prompt = f"generated by {node_id}"
            input_definition = self._resolve_input_definition(
                raw_input_definition=config.get("input_definition"),
                prepared=prepared,
            )
            output_format = self._optional_str(config.get("output_format"))
            prompt = self._build_prompt(
                prompt=prompt,
                input_definition=input_definition,
                resolved_inputs=prepared.get("resolved_inputs", {}),
                output_format=output_format,
            )

            adapter = self._resolve_adapter(config)
            response = adapter.complete(
                LLMCompletionRequest(
                    prompt=prompt,
                    system_prompt=self._optional_str(config.get("system_prompt")),
                    model=self._optional_str(config.get("model")),
                    temperature=self._optional_float(config.get("temperature")),
                    max_tokens=self._optional_int(config.get("max_tokens")),
                )
            )

            normalized_output_format = self._normalize_output_format(output_format)
            rendered_result = self._render_output(text=response.text, output_format=normalized_output_format)

            output: dict[str, Any] = {
                "result": rendered_result,
                "output_format": normalized_output_format,
            }
            structured = self._parse_structured_output(rendered_result, normalized_output_format)
            if structured is not None:
                output["structured_result"] = structured

            return ExecutorResult(
                status="SUCCEEDED",
                output=output,
                input_preview=prompt,
                logs=[
                    f"Prepared {len(prepared['resolved_inputs'])} resolved input(s) for llm_generate."
                ],
            )
        except Exception as exc:  # pragma: no cover - defensive path
            return self.handle_error(exc)

    def _resolve_adapter(self, config: dict[str, Any]) -> LLMCompletionAdapter:
        provider = self._optional_str(config.get("provider"))
        if provider and provider in self._adapters_by_provider:
            return self._adapters_by_provider[provider]
        return self._default_adapter

    def _optional_str(self, value: Any) -> str | None:
        if value is None:
            return None
        text = str(value).strip()
        return text or None

    def _optional_float(self, value: Any) -> float | None:
        if value in (None, ""):
            return None
        return float(value)

    def _optional_int(self, value: Any) -> int | None:
        if value in (None, ""):
            return None
        return int(value)

    def _resolve_input_definition(
        self,
        *,
        raw_input_definition: Any,
        prepared: dict[str, Any],
    ) -> str | None:
        definition_text = self._optional_str(raw_input_definition)
        if definition_text is None:
            return None

        if definition_text.startswith("ref:"):
            return self._resolve_single_reference_definition(definition_text, prepared)

        resolved_multi_refs = self._resolve_multi_reference_definition(definition_text, prepared)
        if resolved_multi_refs is not None:
            return resolved_multi_refs

        return definition_text

    def _resolve_single_reference_definition(self, definition_text: str, prepared: dict[str, Any]) -> str:
        ref_text = definition_text[len("ref:") :].strip()
        resolved_value = self._resolve_reference_value(ref_text=ref_text, prepared=prepared)
        if resolved_value is None:
            return ""
        return resolved_value

    def _resolve_multi_reference_definition(
        self,
        definition_text: str,
        prepared: dict[str, Any],
    ) -> str | None:
        pattern = re.compile(r"\[(?P<title>参照ノード)\s*:\s*(?P<refs>[^\]]*)\]")
        match = pattern.search(definition_text)
        if match is None:
            return None

        refs = [
            item.strip()
            for item in str(match.group("refs") or "").split(",")
            if item.strip()
        ]
        if not refs:
            return definition_text

        formatted_refs: list[str] = []
        for ref in refs:
            normalized_ref = re.sub(r"^ref:\s*", "", ref, flags=re.IGNORECASE).strip()
            resolved = self._resolve_reference_value(ref_text=normalized_ref, prepared=prepared)
            rendered = resolved if resolved is not None else "(not found)"
            if "\n" in rendered:
                formatted_refs.append(f"- {normalized_ref}:\n{textwrap.indent(rendered, '  ')}")
            else:
                formatted_refs.append(f"- {normalized_ref}: {rendered}")

        resolved_block = "\n".join([f"[{match.group('title')}]", *formatted_refs])
        prefix = definition_text[: match.start()].strip()
        suffix = definition_text[match.end() :].strip()

        sections: list[str] = []
        if prefix:
            sections.append(prefix)
        sections.append(resolved_block)
        if suffix:
            sections.append(suffix)
        return "\n\n".join(sections)

    def _resolve_reference_value(self, *, ref_text: str, prepared: dict[str, Any]) -> str | None:
        if "." not in ref_text:
            return None

        source_node_id, output_key = ref_text.split(".", 1)
        source_node_id = source_node_id.strip()
        output_key = output_key.strip()
        if not source_node_id or not output_key:
            return None

        node_outputs = prepared.get("node_outputs") or {}
        source_output = node_outputs.get(source_node_id)
        if not isinstance(source_output, dict):
            return None
        value = source_output.get(output_key)
        if value is None:
            return None
        if isinstance(value, (dict, list)):
            return json.dumps(value, ensure_ascii=False, indent=2, default=str)
        return str(value)

    def _build_prompt(
        self,
        *,
        prompt: str,
        input_definition: str | None,
        resolved_inputs: dict[str, Any],
        output_format: str | None,
    ) -> str:
        sections = [prompt]
        if input_definition:
            sections.append(f"Input definition:\n{input_definition}")
        if resolved_inputs:
            sections.append(
                "Resolved inputs:\n"
                + json.dumps(resolved_inputs, ensure_ascii=False, indent=2, default=str)
            )
        if output_format:
            sections.append(f"Output format:\n{output_format}")
        return "\n\n".join(sections)

    def _normalize_output_format(self, output_format: str | None) -> str:
        normalized = str(output_format or "text").strip().lower().replace("-", "_").replace(" ", "_")
        alias_map = {
            "plain_text": "text",
            "md_json": "markdown_json",
            "md_yaml": "markdown_yaml",
            "md_mermaid": "markdown_mermaid",
        }
        normalized = alias_map.get(normalized, normalized)
        if normalized in self._SUPPORTED_OUTPUT_FORMATS:
            return normalized
        return "text"

    def _render_output(self, *, text: str, output_format: str) -> str:
        if output_format == "markdown_json":
            if self._is_fenced_code_block_for_language(text, "json"):
                return text
            extracted_json = self._extract_first_fenced_code_block_for_language(text, "json")
            if extracted_json is not None:
                return f"```json\n{extracted_json}\n```"
            return f"```json\n{text}\n```"
        if output_format == "markdown_yaml":
            if self._is_fenced_code_block_for_language(text, "yaml"):
                return text
            extracted_yaml = self._extract_first_fenced_code_block_for_language(text, "yaml")
            if extracted_yaml is not None:
                return f"```yaml\n{extracted_yaml}\n```"
            return f"```yaml\n{text}\n```"
        if output_format == "markdown_mermaid":
            normalized_mermaid = self._normalize_mermaid_text(self._extract_mermaid_payload(text))
            return f"```mermaid\n{normalized_mermaid}\n```"
        if output_format == "mermaid":
            return self._normalize_mermaid_text(self._extract_mermaid_payload(text))
        return text

    def _is_fenced_code_block_for_language(self, text: str, language: str) -> bool:
        pattern = re.compile(
            rf"^```\s*{re.escape(language)}\s*\n[\s\S]*\n```\s*$",
            re.IGNORECASE,
        )
        return bool(pattern.match(text.strip()))

    def _extract_first_fenced_code_block_for_language(self, text: str, language: str) -> str | None:
        pattern = re.compile(
            rf"```\s*{re.escape(language)}\s*\n(?P<body>[\s\S]*?)\n```",
            re.IGNORECASE,
        )
        match = pattern.search(text)
        if match is None:
            return None
        return str(match.group("body")).strip()

    def _extract_mermaid_payload(self, text: str) -> str:
        candidate = self._extract_first_fenced_code_block_for_language(text, "mermaid")
        if candidate is not None:
            return candidate

        generic_fence = re.search(r"```\s*(?P<lang>[^`\n]*)\n(?P<body>[\s\S]*?)\n```", text, re.IGNORECASE)
        if generic_fence is not None:
            lang = str(generic_fence.group("lang") or "").strip().lower()
            body = str(generic_fence.group("body") or "")
            if "mermaid" in lang:
                return body

        return text

    def _normalize_mermaid_text(self, text: str) -> str:
        normalized = text.replace("\r\n", "\n").replace("\r", "\n")
        for _ in range(3):
            wrapped = re.match(r"^```\s*[a-zA-Z0-9_+-]*\s*\n(?P<body>[\s\S]*?)\n```\s*$", normalized.strip())
            if wrapped is None:
                break
            normalized = str(wrapped.group("body"))

        lines = [line.rstrip() for line in normalized.split("\n")]
        while lines and not lines[0].strip():
            lines.pop(0)
        while lines and not lines[-1].strip():
            lines.pop()
        if lines and re.match(r"^```\s*[a-zA-Z0-9_+-]*\s*$", lines[0].strip()):
            lines = lines[1:]
        if lines and lines[-1].strip() == "```":
            lines = lines[:-1]
        if lines and lines[0].strip().lower() in {"mermaid", "markdown_mermaid"}:
            lines = lines[1:]
        if lines:
            lines[0] = re.sub(r"^workflow(\s+(TD|LR|BT|RL)\b)", r"flowchart\1", lines[0], flags=re.IGNORECASE)
        lines = self._sanitize_mermaid_lines(lines)
        return "\n".join(lines).strip()

    def _sanitize_mermaid_lines(self, lines: list[str]) -> list[str]:
        if not lines:
            return lines

        header = lines[0].strip().lower()
        is_flowchart = header.startswith("flowchart")
        if not is_flowchart:
            return lines

        sanitized: list[str] = []
        note_pattern = re.compile(
            r"^\s*note\s+(?:left|right)\s+of\s+\S+\s*:\s*(?P<text>.+)$|^\s*note\s+over\s+\S+\s*:\s*(?P<text_over>.+)$",
            re.IGNORECASE,
        )

        for index, line in enumerate(lines):
            if index == 0:
                sanitized.append(line)
                continue

            match = note_pattern.match(line)
            if match is None:
                sanitized.append(line)
                continue

            note_text = str(match.group("text") or match.group("text_over") or "").strip()
            if note_text:
                sanitized.append(f"  %% NOTE: {note_text}")

        return sanitized

    def _unwrap_markdown_code_block(self, text: str) -> str:
        match = re.match(r"^```[a-zA-Z0-9_+-]*\n(?P<body>[\s\S]*?)\n```\s*$", text.strip())
        if match is None:
            return text
        return str(match.group("body"))

    def _parse_structured_output(self, text: str, output_format: str | None) -> Any | None:
        if not output_format:
            return None
        normalized = self._normalize_output_format(output_format)
        payload = self._unwrap_markdown_code_block(text)

        if normalized in {"json", "markdown_json"}:
            try:
                return json.loads(payload)
            except Exception:
                return None

        if normalized in {"yaml", "markdown_yaml"}:
            try:
                parsed = yaml.safe_load(payload)
            except Exception:
                return None
            if isinstance(parsed, (dict, list)):
                return parsed
            return None

        return None
